import { AdminShell } from "@/components/admin/AdminShell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { assets } from "@/lib/assets";
import { CalendarClock, Clock3, Edit3, Gift, Plus, Timer, X } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

const offers = [
  { name: "Sunday Family Combo", detail: "Chicken + Mutton + Prawns", price: 1499, previous: 1719, status: "Active", dates: "21–22 Sep", image: assets.hero },
  { name: "Rohu Weekday Saver", detail: "20% off 1 kg Rohu", price: 669, previous: 749, status: "Scheduled", dates: "24–26 Sep", image: assets.rohu },
  { name: "Prawn Celebration", detail: "₹100 off 500 g pack", price: 529, previous: 629, status: "Expired", dates: "12–14 Sep", image: assets.prawns },
];

export default function AdminOffers() {
  const [editor, setEditor] = useState(false);
  return (
    <AdminShell title="Offers & combos" subtitle="Schedule campaigns that publish and expire automatically." action={<Button onClick={() => setEditor(true)} className="h-11 rounded-full bg-[#B4232C] px-5 font-black text-white hover:bg-[#951D24]"><Plus className="size-4" /> Create offer</Button>}>
      <div className="mb-7 grid gap-4 md:grid-cols-3"><Metric icon={Gift} label="Active offers" value="3" tone="red" /><Metric icon={CalendarClock} label="Scheduled" value="2" tone="green" /><Metric icon={Timer} label="Expiring in 48h" value="1" tone="amber" /></div>
      <div className="grid gap-5 xl:grid-cols-3">{offers.map((offer) => <article key={offer.name} className="overflow-hidden rounded-[1.5rem] bg-white shadow-[0_12px_34px_rgba(61,33,27,.055)] ring-1 ring-black/[0.04]"><div className="relative aspect-[16/8] overflow-hidden"><img src={offer.image} alt="" className="size-full object-cover" /><span className={`absolute left-4 top-4 rounded-full px-3 py-1.5 text-[0.68rem] font-black ${offer.status === "Active" ? "bg-[#E5F3E3] text-[#267345]" : offer.status === "Scheduled" ? "bg-[#FFF0D2] text-[#8A5A00]" : "bg-[#EEEAE8] text-[#6E625E]"}`}>{offer.status}</span></div><div className="p-5"><p className="text-xs font-black uppercase tracking-[0.14em] text-[#B4232C]">{offer.dates}</p><h2 className="mt-2 text-lg font-black">{offer.name}</h2><p className="mt-1 text-sm text-muted-foreground">{offer.detail}</p><div className="mt-5 flex items-end justify-between"><div><span className="text-xl font-black">₹{offer.price}</span><span className="ml-2 text-sm text-muted-foreground line-through">₹{offer.previous}</span></div><Button onClick={() => setEditor(true)} variant="outline" size="icon" className="rounded-full bg-white"><Edit3 className="size-4" /></Button></div></div></article>)}</div>
      <div className="mt-7 rounded-[1.5rem] bg-[#17110F] p-6 text-white sm:p-8"><div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-black uppercase tracking-[0.15em] text-[#F2989C]">Automatic expiry</p><h2 className="mt-2 text-xl font-black">No more midnight offer takedowns</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-white/55">Scheduled campaigns are displayed from the server-provided start time and disappear automatically after the end time.</p></div><span className="grid size-14 shrink-0 place-items-center rounded-2xl bg-white/10"><Clock3 className="size-6 text-[#72B556]" /></span></div></div>
      {editor && <div className="fixed inset-0 z-[70]"><button className="absolute inset-0 bg-black/45 backdrop-blur-sm" onClick={() => setEditor(false)} aria-label="Close offer editor" /><aside className="absolute inset-y-0 right-0 w-full max-w-xl overflow-y-auto bg-[#FFFDF9] p-5 shadow-2xl sm:p-8"><div className="flex items-start justify-between"><div><p className="text-xs font-black uppercase tracking-[0.15em] text-[#B4232C]">Campaign editor</p><h2 className="mt-2 font-display text-3xl font-black">Create an offer</h2></div><Button variant="ghost" size="icon" className="rounded-full bg-white" onClick={() => setEditor(false)}><X className="size-5" /></Button></div><div className="mt-8 space-y-5"><Field label="Offer name"><Input className="h-12 rounded-xl bg-white" placeholder="Sunday Special Ilish Combo" /></Field><Field label="Choose product or combo"><select className="h-12 w-full rounded-xl border border-input bg-white px-3 text-sm"><option>Sunday Family Combo</option><option>Fresh Rohu Curry Cut</option><option>Cleaned Tiger Prawns</option></select></Field><div className="grid gap-5 sm:grid-cols-2"><Field label="Offer price"><Input className="h-12 rounded-xl bg-white" placeholder="₹ 1,499" /></Field><Field label="Coupon code (optional)"><Input className="h-12 rounded-xl bg-white" placeholder="SUNDAY1499" /></Field></div><div className="grid gap-5 sm:grid-cols-2"><Field label="Starts"><Input type="datetime-local" className="h-12 rounded-xl bg-white" /></Field><Field label="Ends"><Input type="datetime-local" className="h-12 rounded-xl bg-white" /></Field></div><div className="flex items-center justify-between rounded-[1.2rem] bg-[#EAF4E8] p-5"><div><p className="font-black text-[#275F3C]">Publish automatically</p><p className="mt-1 text-xs text-[#557662]">Start and end using Kolkata time.</p></div><Switch defaultChecked /></div><div className="mt-8 flex gap-3"><Button variant="outline" className="h-12 flex-1 rounded-full bg-white font-black">Save draft</Button><Button onClick={() => { toast.success("Offer scheduled in prototype"); setEditor(false); }} className="h-12 flex-1 rounded-full bg-[#B4232C] font-black text-white hover:bg-[#951D24]">Schedule offer</Button></div></div></aside></div>}
    </AdminShell>
  );
}

function Metric({ icon: Icon, label, value, tone }: { icon: typeof Gift; label: string; value: string; tone: string }) { return <div className="flex items-center gap-4 rounded-[1.25rem] bg-white p-5 shadow-[0_10px_30px_rgba(61,33,27,.045)] ring-1 ring-black/[0.04]"><span className={`grid size-11 place-items-center rounded-2xl ${tone === "red" ? "bg-[#FBE8E7] text-[#B4232C]" : tone === "green" ? "bg-[#E8F3E5] text-[#267345]" : "bg-[#FFF0D2] text-[#8A5A00]"}`}><Icon className="size-5" /></span><div><p className="text-xs font-bold text-muted-foreground">{label}</p><p className="mt-1 text-2xl font-black">{value}</p></div></div>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="space-y-2"><Label className="font-bold">{label}</Label>{children}</div>; }
